[project]
name = "pixi_container_snake"
version = "0.1.0"
description = "Add a short description here"
authors = ["Michael O'Hanrahan <104068149+michaelohanrahan@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "win-64"]


[tasks]

[dependencies]
python="3.11"
snakemake="8.18"

[target.linux-64.dependencies]
ncurses = "6.4.*"
